on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v3
      - name: Build binari and doc
        run: |
          alr toolchain
          rm -f -v alire.toml
          LIBRARY_TYPE=relocatable alr get --build libhello
          ls -lR

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
