on: [push, pull_request]

permissions: write-all

name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: macos-13-xlarge
    steps:
      - run: |
          uname -a
          which gcc
          sysctl -n machdep.cpu.brand_string
          gcc -v
