on:
  push:
    branches:
      - master
      - stable
      - alr_toolchain
name: Build binaries
jobs:
  build:
    name: Build and deploy

    # The only purpose of this workflow is to upload builds, so do not run it
    # in contexts when upload is impossible: only the official repository has
    # the secrets to upload binaries to Bintray.
    # if: ${{ github.repository == 'AdaCore/libadalang' }}

    strategy:
      fail-fast: false
      matrix: # Build debug and production
#        debug: ['', 'debug']      # '' if production, 'debug' for debug
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf input
        shell: bash
      - name: Install iconv and gmp (Windows only)
        if: ${{ runner.os == 'Windows' }}
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            mingw64/mingw-w64-x86_64-libiconv
            mingw64/mingw-w64-x86_64-gmp
      - name: Get libadalang
        uses: actions/checkout@v2
      - name: Get gprbuild for libgpr
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gprbuild
          path: gprbuild
          fetch-depth: 0  # To be able do `git revert`
#      - name: Revert a libgpr patch (MacOS X only)
        # The latest libgpr doesn't support GNAT CE 2020, but on MacOS X we
        # don't have GNAT CE 2021. Let's revert this commit for now.
#        if: ${{ runner.os == 'macOS' }}
#        run: git -C gprbuild revert --no-edit 3341766255bf5ab90fe05a8e162894b7830adca6
      - name: Get gnatcoll core
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gnatcoll-core
          path: gnatcoll-core
      - name: Get gnatcoll iconv/gmp
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gnatcoll-bindings
          path: gnatcoll-bindings
      - name: Get langkit
        uses: actions/checkout@v2
        with:
          repository: AdaCore/langkit
          path: langkit
          fetch-depth: 0  # all branches
      - name: Try to checkout langkit's branch
        shell: bash
        run: (cd langkit; git checkout ${{ github.ref }} || true)
      - uses: actions/cache@v2
        with:
          path: ./cached_gnat
          key: ${{ runner.os }}-alire-2021
#      - name: Install toolchain
#        uses: ada-actions/toolchain@ce2021
#        with:
#          distrib: community
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v1
        # fails on windows, can't find gprbuild
#        continue-on-error: true
        with:
          toolchain: gnat_native^11 gprbuild^21 --disable-assistant
          toolchain_dir: ./cached_gnat
