on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install e3-core==22.1.0

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
