on: [push, pull_request]

permissions: write-all

name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - run: |
          curl -L 'https://www.dropbox.com/scl/fi/x9wzg3avorl9h28ktml6r/lal.tar?rlkey=fpwuko9ct8ize6g10spxaw44o&dl=1' | tar xvf -
          ls -la
          umask
        shell: bash

      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}