on:
  push:
    branches:
      - master
name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Get gprbuild
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gprbuild
          path: gprbuild
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_native^11 gprbuild^21 --disable-assistant
          toolchain_dir: ./cached_gnat
