on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - name: Check locale
        run: |
          sudo sed -i -e '/uk_UA.UTF-8/s/# //' /etc/locale.gen
          sudo locale-gen

          locale -a

          #      - name: Setup upterm session
          #        uses: lhotari/action-upterm@v1
