on: [push, pull_request]

permissions: write-all

name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_native gprbuild
      - name: Build sources
        run: |
          set -e -x
          alr build
          ulimit -c unlimited
          mkdir core-dump
          echo "$PWD/core-dump/corefile-%e-%p-%t" | sudo tee /proc/sys/kernel/core_pattern
          ./bin/test | true

      - uses: actions/upload-artifact@master
        with:
          name: crashes
          path: ./core-dump/*
