on: push

name: Build
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v5
      - name: Check locale
        run: alr get --build hp41cx_tools
