on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Get sources
        uses: actions/checkout@v2
#      - name: Get GNATdoc
#        uses: reznikmm/setup-gnatdoc@main
      - name: Install gprbuild
        run: |
          curl -L https://github.com/simonjwright/alire-index.mac/releases/download/toolchain-13.2.1/gprbuild-macos-aarch64-23.0.2.tar.gz | tar xzvf -
          echo $PWD/gprbuild/bin >> $GITHUB_PATH
      - name: Install Alire
#        uses: alire-project/setup-alire@v3
        run: |
          curl -L -O https://github.com/simonjwright/alire-index.mac/releases/download/alr-2.0.1-bin-aarch64-macos/alr-2.0.1-bin-aarch64-macos.zip
          unzip alr-2.0.1-bin-aarch64-macos.zip
          echo $PWD/bin >> $GITHUB_PATH
      - name: Build binari and doc
        run: |
          #alr index --reset-community
          alr index --add git+https://github.com/reznikmm/alire-index.git#topic/gcc-14-mac --name mac
          alr toolchain --select gnat_native^14
          alr toolchain
          alr exec gcc -- -v
          alr build
          # gnatdoc -P test.gpr --output-dir output --backend html

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
