on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v3
      - name: Do something
        run: |
          git clone https://github.com/AdaCore/gnatcoll-core.git gnatcoll
          cp -v gnatcoll.toml gnatcoll/alire.toml
          alr --non-interactive pin gnatcoll --use=./gnatcoll
          alr --non-interactive -v -v exec env
          alr --non-interactive exec env | grep GPR_PROJECT_PATH
          alr build

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
