on: [push, pull_request]

permissions: write-all

name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - run: |
          git config --global core.autocrlf input
          mkdir -p ~/.config/alire
          echo '[msys2]' >> ~/.config/alire/config.toml
          echo 'install_dir = "C:\\msys64"' >> ~/.config/alire/config.toml
        shell: bash

      - run: |
           echo $PATH
           pacman --noconfirm -S mingw64/mingw-w64-x86_64-libiconv mingw64/mingw-w64-x86_64-gmp
        shell: c:\msys64\usr\bin\bash.exe -l -e -o pipefail {0}
        env:
          MSYSTEM: MINGW64

      - name: Get sources
        uses: actions/checkout@v2

      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v2
        with:
          toolchain: gnat_native gprbuild

      - name: Set Windows PATH
        shell: cmd
        run: |
          alr get gnat_native --dirname > %temp%\gnatdir.txt
          set /P gnatdir=<%temp%\gnatdir.txt
          echo %USERPROFILE%.config\alire\cache\dependencies\%gnatdir%\bin >> %GITHUB_PATH%

          alr get gprbuild --dirname > %temp%\gnatdir.txt
          set /P gnatdir=<%temp%\gnatdir.txt
          echo %USERPROFILE%.config\alire\cache\dependencies\%gnatdir%\bin >> %GITHUB_PATH%

      - name: Build sources
        shell: bash
        run: |
          set -e -x
          echo $PATH
          ls -la
          rm -rfv alire.toml
          alr --non-interactive get xmlada
