on:
  push:
    tags:
      - 2*.*.*
permissions: write-all

name: Build binaries
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Run release.sh
        run: .github/workflows/release.sh ${{ secrets.GITHUB_TOKEN }}
