on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Build binari and doc
        run: |
          uname -a
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

